#!/bin/bash
die() {
  echo "$@"
  exit 1
}

for binary in maim notify-send xdotool; do
  which "$binary" &>/dev/null || die "Required '$binary' is not available."
done

output_dir="$HOME/Pictures/screenshots"
output="$output_dir/$(date +'%Y-%m-%d-%H%M%S').png"
color=1,1,1,0.1
source=''

mkdir -p "$output_dir"
while getopts rcw opt; do
  case $opt in
    r) ;;
    w) source="-i $(xdotool getactivewindow)" ;;
    c) source="-s -c $color";;
    \?) die "Invalid option: -$OPTARG" ;;
  esac
done

maim "$source" "$output" &&
notify-send "Screenshot was saved to $output"
